# Generated by Django 4.1.4 on 2022-12-30 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(150)], verbose_name='Glucose level')),
                ('bmi', models.FloatField(blank=True, default=None, help_text=None, null=True, verbose_name='BMI')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(300)], verbose_name='Blood pressure systolic')),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Blood pressure diastolic')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(110)], verbose_name='Age')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stroke', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
