# Generated by Django 4.1.3 on 2022-12-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailphoneuser',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='phone.device'),
        ),
    ]
