# Generated by Django 4.1.3 on 2022-12-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_emailphoneuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailphoneuser',
            name='device',
        ),
    ]
