# Generated by Django 4.1.3 on 2022-12-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_remove_emailphoneuser_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailphoneuser',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='phone.device'),
        ),
    ]
