# Generated by Django 4.1.4 on 2023-01-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('next_delivery_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
