# Generated by Django 4.1.3 on 2022-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailphoneuser',
            name='date_locked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
