# Generated by Django 4.1.4 on 2023-01-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_emailphoneuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailphoneuser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
