# Generated by Django 4.1 on 2023-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_remove_emailphoneuser_secret_key_magiclink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
