# Generated by Django 4.1 on 2023-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0016_book_booktranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktranslation',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
